// Generated by scripts/prepare-campus.mjs. Filenames change with content.
export const SCENE_ASSETS={
  "high": "assets/campus/high-9788260d177c.scene.gz",
  "medium": "assets/campus/medium-b700cbc24f37.scene.gz"
};
