// Generated by scripts/prepare-campus.mjs. Filenames change with content.
export const SCENE_ASSETS={
  "high": "assets/campus/high-4347a7c2f233.scene.gz",
  "medium": "assets/campus/medium-96878be263ee.scene.gz"
};
