// Generated by scripts/prepare-campus.mjs. Filenames change with content.
export const SCENE_ASSETS={
  "high": "assets/campus/high-94836c8deb31.scene.gz",
  "medium": "assets/campus/medium-ece01d800e2c.scene.gz"
};
