// Build both prepared models after geometry changes; users download no extra runtime code.
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {execFileSync} from 'node:child_process';
import {gzipSync} from 'node:zlib';
import {createHash} from 'node:crypto';

const scene=new URL('../explore/scene/',import.meta.url);
if(!process.argv[2]){
  // Keep browser and worker builders identical apart from their module paths.
  for(const name of ['campus.js','siteworks.js','roofscape.js','garden-paths.js','stair-jaali.js','stair-flight.js','entrance-details.js','entrance-paths.js','garden.js','landscape-courtyard.js','landscape-beds.js','courtyard-layout.js','bridge-route.js','architecture-detail.js','entry-config.js','navigation-config.js','campus-transfer.js']){
    const source=await readFile(new URL(name,scene),'utf8');
    await writeFile(new URL('worker/'+name,scene),source.replaceAll("from 'three';","from '../assets/three.module.js';").replaceAll("from 'three/addons/","from './assets/addons/"));
  }
  const assets={};
  for(const quality of ['high','medium']){
    console.log('Preparing '+quality+' model…');
    const output=execFileSync(process.execPath,[fileURLToPath(import.meta.url),quality],{encoding:'utf8',maxBuffer:1024*1024});
    const result=JSON.parse(output.trim().split('\n').at(-1));
    assets[quality]=result.file;console.log(JSON.stringify(result));
  }
  await writeFile(new URL('scene-assets.js',scene),'// Generated by scripts/prepare-campus.mjs. Filenames change with content.\nexport const SCENE_ASSETS='+JSON.stringify(assets,null,2)+';\n');
}else{
  const quality=process.argv[2];if(!['high','medium'].includes(quality))throw new Error('Unknown model quality');
  const {buildCampus}=await import('../explore/scene/worker/campus.js');
  const {packCampus}=await import('../explore/scene/worker/campus-transfer.js');
  const {encodeCampusBinary}=await import('../explore/scene/scene-binary.js');
  const {PROJECTS}=await import('../explore/scene/projects.js');
  const {auditFacade}=await import('./check-roof-clearance.mjs');
  const THREE=await import('../explore/scene/assets/three.module.js');
  const {mergeVertices}=await import('../explore/scene/worker/assets/addons/utils/BufferGeometryUtils.js');
  const campus=buildCampus(PROJECTS,{quality}),compacted=new Map();
  function compact(mesh){
    if(!mesh.geometry)return;
    const original=mesh.geometry;
    if(!compacted.has(original)){
      const geometry=mergeVertices(original,1e-4);
      for(const [name,Type,max] of [['normal',Int16Array,32767],['color',Uint8Array,255]]){
        const attribute=geometry.attributes[name];if(!attribute)continue;
        const values=new Type(attribute.count*attribute.itemSize);
        for(let i=0;i<values.length;i++)values[i]=Math.round(Math.max(name==='normal'?-1:0,Math.min(1,attribute.array[i]))*max);
        geometry.setAttribute(name,new THREE.BufferAttribute(values,attribute.itemSize,true));
      }
      geometry.computeBoundingSphere();compacted.set(original,geometry);
    }
    mesh.geometry=compacted.get(original);
  }
  campus.root.traverse(compact);campus.walkSurfaces.forEach(s=>compact(s.mesh));
  const audit=auditFacade(campus);
  if(audit.violations||audit.uncovered||audit.minimumGap<.08)throw new Error('Roof clearance failed: '+JSON.stringify(audit));
  const bytes=gzipSync(Buffer.from(encodeCampusBinary(packCampus(campus))),{level:9});
  const hash=createHash('sha256').update(bytes).digest('hex').slice(0,12),file='assets/campus/'+quality+'-'+hash+'.scene.gz';
  await mkdir(new URL('assets/campus/',scene),{recursive:true});
  await writeFile(new URL(file,scene),bytes);
  console.log(JSON.stringify({quality,file,bytes:bytes.length,audit}));
}
